name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip and testing tools
        run: |
          python -m pip install black pytest pylint
      - name: Check formatting with black
        run: |
          black --check alarmpy
      - name: Run pylint
        run: |
          pylint -j 0 -d R,C alarmpy
      - name: Test with pytest
        run: |
          pytest
