name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip and testing tools
        run: |
          python -m pip install --upgrade pipenv
          pipenv install -d
      - name: Check formatting with black
        run: |
          pipenv run formatcheck
      - name: Run pylint
        run: |
          pipenv run lint
      - name: Test with pytest
        run: |
          pipenv run test
